import { Registry } from '../registry-schema'

export const registry_ui: Registry = [
  {
    name: 'button',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-slot', '@ahmedayob/duck-shortcut'],
    registryDependencies: ['tooltip', 'command', 'badge'],
    root_folder: 'registry-ui-components/button',
    files: [],
  },
  {
    name: 'badge',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-slot'],
    registryDependencies: ['tooltip'],
    root_folder: 'registry-ui-components/badge',
    files: [],
  },
  {
    name: 'tooltip',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-tooltip'],
    registryDependencies: [],
    root_folder: 'registry-ui-components/tooltip',
    files: [],
  },
  {
    name: 'accordion',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-accordion'],
    registryDependencies: [],
    root_folder: 'registry-ui-components/accordion',
    files: [],
  },
  {
    name: 'toggle',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-toggle'],
    registryDependencies: [],
    root_folder: 'registry-ui-components/toggle',
    files: [],
  },
  {
    name: 'toggle-group',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-toggle-group'],
    registryDependencies: [],
    root_folder: 'registry-ui-components/toggle-group',
    files: [],
  },
  {
    name: 'toast',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-toast'],
    registryDependencies: [],
    root_folder: 'registry-ui-components/toast',
    files: [],
  },
  {
    name: 'sonner',
    type: 'registry:ui',
    dependencies: ['sonner', 'next-themes'],
    registryDependencies: [],
    root_folder: 'registry-ui-components/sonner',
    files: [],
  },
  {
    name: 'textarea',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'registry-ui-components/textarea',
    files: [],
  },
  {
    name: 'tabs',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-tabs'],
    registryDependencies: [],
    root_folder: 'registry-ui-components/tabs',
    files: [],
  },
  {
    name: 'table',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [
      'combobox',
      'input',
      'pagination',
      'scrollarea',
      'dropdown',
      'command',
      'button',
      'checkbox',
      'badge',
      'context-menu',
      'tooltip',
    ],
    root_folder: 'registry-ui-components/table',
    files: [],
  },
]
