// @ts-nocheck
// This file is autogenerated by scripts/build-registry/main/main.ts
// Do not edit this file directly.
import * as React from 'react'

export const Index: Record<string, any> = {
  button: {
    name: 'button',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['tooltip', 'command', 'badge'],
    files: [
      {
        path: 'button/button.constants.ts',
        type: 'registry:ui',
      },
      {
        path: 'button/button.tsx',
        type: 'registry:ui',
      },
      {
        path: 'button/button.types.ts',
        type: 'registry:ui',
      },
      {
        path: 'button/index.ts',
        type: 'registry:ui',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-ui-duckui/button')
    ),
    source: '/registry-ui-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-1': {
    name: 'button-1',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-1.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-1')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-10': {
    name: 'button-10',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-10.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-10')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-11': {
    name: 'button-11',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-11.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-11')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-12': {
    name: 'button-12',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-12.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-12')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-13': {
    name: 'button-13',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-13.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-13')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-14': {
    name: 'button-14',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-14.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-14')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-15': {
    name: 'button-15',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-15.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-15')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-16': {
    name: 'button-16',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-16.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-16')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-17': {
    name: 'button-17',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-17.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-17')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-18': {
    name: 'button-18',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-18.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-18')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-19': {
    name: 'button-19',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-19.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-19')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-2': {
    name: 'button-2',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-2.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-2')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-20': {
    name: 'button-20',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-20.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-20')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-21': {
    name: 'button-21',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-21.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-21')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-22': {
    name: 'button-22',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-22.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-22')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-23': {
    name: 'button-23',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-23.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-23')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-24': {
    name: 'button-24',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-24.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-24')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-25': {
    name: 'button-25',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-25.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-25')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-26': {
    name: 'button-26',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-26.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-26')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-27': {
    name: 'button-27',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-27.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-27')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-28': {
    name: 'button-28',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-28.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-28')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-29': {
    name: 'button-29',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-29.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-29')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-3': {
    name: 'button-3',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-3.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-3')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-30': {
    name: 'button-30',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-30.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-30')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-31': {
    name: 'button-31',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-31.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-31')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-32': {
    name: 'button-32',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-32.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-32')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-4': {
    name: 'button-4',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-4.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-4')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-5': {
    name: 'button-5',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-5.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-5')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-6': {
    name: 'button-6',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-6.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-6')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-7': {
    name: 'button-7',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-7.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-7')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-8': {
    name: 'button-8',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-8.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-8')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
  'button-9': {
    name: 'button-9',
    description: '',
    type: 'registry:example',
    registryDependencies: ['button'],
    files: [
      {
        path: 'button/button-9.tsx',
        type: 'registry:example',
      },
    ],
    component: React.lazy(
      () => import('@gentelduck/registry-examples-duckui/button/button-9')
    ),
    source: '/registry-examples-duckui/src/button',
    category: '',
    subcategory: '',
    chunks: [],
  },
}
