// Environment Variables

import { config } from 'dotenv'
import { envSchema } from './zod'

config()
// POSTGRES
const POSTGRES_HOST = process.env.POSTGRES_HOST
const POSTGRES_PORT = process.env.POSTGRES_PORT
const POSTGRES_DB = process.env.POSTGRES_DB
const POSTGRES_USER = process.env.POSTGRES_USER
const POSTGRES_PASSWORD = process.env.POSTGRES_PASSWORD

// MINIO
const MINIO_ENDPOINT = process.env.MINIO_ENDPOINT
const MINIO_BUCKET = process.env.MINIO_BUCKET
const MINIO_REGION = process.env.MINIO_REGION
const MINIO_ROOT_USER = process.env.MINIO_ROOT_USER
const MINIO_ROOT_PASSWORD = process.env.MINIO_ROOT_PASSWORD
const MINIO_ACCESS_KEY = process.env.MINIO_ACCESS_KEY
const MINIO_SECRET_KEY = process.env.MINIO_SECRET_KEY
const MINIO_BUCKET_REGION = process.env.MINIO_BUCKET_REGION

// Connection String
const CONNECTIONSTRING = `postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}`

export const ENV = envSchema.parse({
  POSTGRES_HOST,
  POSTGRES_PORT,
  POSTGRES_DB,
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  CONNECTIONSTRING,
  MINIO_ENDPOINT,
  MINIO_BUCKET,
  MINIO_REGION,
  MINIO_ROOT_USER,
  MINIO_ROOT_PASSWORD,
  MINIO_ACCESS_KEY,
  MINIO_SECRET_KEY,
  MINIO_BUCKET_REGION,
})
