packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.59.15
  '@trpc/client': ^11.0.0-rc.477
  '@trpc/react-query': ^11.0.0-rc.477
  '@trpc/server': ^11.0.0-rc.477
  '@types/node': ^20.17.18
  tailwindcss: ^4
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.11
    '@types/react-dom': ^18.3.1
  react19:
    react: ^19.0.0
    react-dom: ^19.0.0
    '@types/react': ^19
    '@types/react-dom': ^19
