import type { Metadata } from 'next'
import './globals.css'
import { cn } from '@gentelduck/libs/cn'
import { ThemeProvider } from '~/components/providers'
import { DefaultSonner } from '@gentelduck/registry-ui-duckui/sonner'
import { ThemeSwitcher } from '~/components/theme-switcher'
import { TailwindIndicator } from '~/components/layouts/tailwind-indicator'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="/fonts/Geist-VF.woff2"
          rel="preload"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          href="/fonts/JetBrainsMono-MD.woff2"
          rel="preload"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body className={cn('min-h-svh bg-background font-sans antialiased')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          enableColorScheme
        >
          <div vaul-drawer-wrapper="">
            <div className="relative flex min-h-svh flex-col bg-background">
              {children}
            </div>
          </div>
          <ThemeSwitcher />
          <DefaultSonner />
          {process.env.NODE_ENV === 'development' && <TailwindIndicator />}
        </ThemeProvider>
      </body>
    </html>
  )
}
