// @ts-nocheck
// This file is autogenerated by scripts/build-registry/main/main.ts
// Do not edit this file directly.
import * as React from 'react'

export const Index: Record<string, any> = {
  button: {
    name: 'button',
    description: '',
    type: 'registry:ui',
    registryDependencies: undefined,
    files: [
      [
        { path: 'registry-ui-components/button/button.constants.ts', type: 'registry:ui' },
        { path: 'registry-ui-components/button/button.tsx', type: 'registry:ui' },
        { path: 'registry-ui-components/button/button.types.ts', type: 'registry:ui' },
        { path: 'registry-ui-components/button/index.ts', type: 'registry:ui' },
      ],
    ],
    component: React.lazy(() => import('@/registry/registry-ui-components/button')),
    source: '',
    category: '',
    subcategory: '',
    chunks: [],
  },
}
