// @ts-nocheck
// This file is autogenerated by scripts/build-registry/main/main.ts
// Do not edit this file directly.
import * as React from 'react'

export const Index: Record<string, any> = {
  button: {
    name: 'button',
    description: '',
    type: 'registry:ui',
    registryDependencies: ['tooltip', 'command', 'badge'],
    files: [
      {
        path: 'button/button.constants.ts',
        type: 'registry:ui',
      },
      {
        path: 'button/button.tsx',
        type: 'registry:ui',
      },
      {
        path: 'button/button.types.ts',
        type: 'registry:ui',
      },
      {
        path: 'button/index.ts',
        type: 'registry:ui',
      },
    ],
    component: React.lazy(() => import('@gentleduck/registry-ui-duckui/button')),
    source: '',
    category: '',
    subcategory: '',
    chunks: [],
  },
}
