import { Registry } from '../registry-schema'

export const registry_ui: Registry = [
  {
    name: 'button',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-slot', '@ahmedayob/duck-shortcut'],
    registryDependencies: ['tooltip', 'command', 'badge'],
    root_folder: 'button',
    files: [],
  },
  // {
  //   name: 'badge',
  //   type: 'registry:ui',
  //   dependencies: ['@radix-ui/react-slot'],
  //   registryDependencies: ['tooltip'],
  //   root_folder: 'badge',
  //   files: [],
  // },
  // {
  //   name: 'tooltip',
  //   type: 'registry:ui',
  //   dependencies: ['@radix-ui/react-tooltip'],
  //   registryDependencies: [],
  //   root_folder: 'tooltip',
  //   files: [],
  // },
  // {
  //   name: 'accordion',
  //   type: 'registry:ui',
  //   dependencies: ['@radix-ui/react-accordion'],
  //   registryDependencies: [],
  //   root_folder: 'accordion',
  //   files: [],
  // },
  // {
  //   name: 'toggle',
  //   type: 'registry:ui',
  //   dependencies: ['@radix-ui/react-toggle'],
  //   registryDependencies: [],
  //   root_folder: 'toggle',
  //   files: [],
  // },
  // {
  //   name: 'toggle-group',
  //   type: 'registry:ui',
  //   dependencies: ['@radix-ui/react-toggle-group'],
  //   registryDependencies: [],
  //   root_folder: 'toggle-group',
  //   files: [],
  // },
  // {
  //   name: 'toast',
  //   type: 'registry:ui',
  //   dependencies: ['@radix-ui/react-toast'],
  //   registryDependencies: [],
  //   root_folder: 'toast',
  //   files: [],
  // },
  // {
  //   name: 'sonner',
  //   type: 'registry:ui',
  //   dependencies: ['sonner', 'next-themes'],
  //   registryDependencies: [],
  //   root_folder: 'sonner',
  //   files: [],
  // },
  // {
  //   name: 'textarea',
  //   type: 'registry:ui',
  //   dependencies: [],
  //   registryDependencies: [],
  //   root_folder: 'textarea',
  //   files: [],
  // },
  {
    name: 'tabs',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-tabs'],
    registryDependencies: [],
    root_folder: 'tabs',
    files: [],
  },
  // {
  //   name: 'table',
  //   type: 'registry:ui',
  //   dependencies: [],
  //   registryDependencies: [
  //     'combobox',
  //     'input',
  //     'pagination',
  //     'scroll-area',
  //     'dropdown',
  //     'command',
  //     'button',
  //     'checkbox',
  //     'badge',
  //     'context-menu',
  //     'tooltip',
  //   ],
  //   root_folder: 'table',
  //   files: [],
  // },
  // {
  //   name: 'upload',
  //   type: 'registry:ui',
  //   dependencies: [],
  //   registryDependencies: [
  //     'alert-dialog',
  //     'input',
  //     'context-menu',
  //     'scroll-area',
  //     'button',
  //   ],
  //   root_folder: 'upload',
  //   files: [],
  // },
  // {
  //   name: 'alert-dialog',
  //   type: 'registry:ui',
  //   dependencies: [],
  //   registryDependencies: [],
  //   root_folder: 'alert-dialog',
  //   files: [],
  // },
  // {
  //   name: 'drawer',
  //   type: 'registry:ui',
  //   dependencies: [],
  //   registryDependencies: [],
  //   root_folder: 'drawer',
  //   files: [],
  // },
]
