import { Registry } from '../registry-schema'

export const registry_ui: Registry = [
  {
    name: 'accordion',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'accordion',
  },
  {
    name: 'alert-dialog',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'alert-dialog',
  },
  {
    name: 'badge',
    type: 'registry:ui',
    dependencies: ['@radix-ui/react-slot'],
    registryDependencies: ['tooltip'],
    root_folder: 'badge',
  },
  {
    name: 'button',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'button',
  },
  {
    name: 'card',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'card',
  },
  {
    name: 'drawer',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'drawer',
  },
  {
    name: 'hover-card',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'hover-card',
  },
  {
    name: 'input',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'input',
  },
  {
    name: 'label',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'label',
  },
  {
    name: 'progress',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'progress',
  },
  {
    name: 'radio-group',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'radio-group',
  },
  {
    name: 'scroll-area',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'scroll-area',
  },
  {
    name: 'select',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'select',
  },
  {
    name: 'separator',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'separator',
  },
  {
    name: 'sheet',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'sheet',
  },
  {
    name: 'skeleton',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'skeleton',
  },
  {
    name: 'slider',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'slider',
  },
  {
    name: 'switch',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'switch',
  },
  {
    name: 'sonner',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'sonner',
  },
  {
    name: 'table',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'table',
  },
  {
    name: 'tabs',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'tabs',
  },
  {
    name: 'textarea',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'textarea',
  },
  {
    name: 'toast',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'toast',
  },
  {
    name: 'toggle',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'toggle',
  },
  {
    name: 'toggle-group',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'toggle-group',
  },
  {
    name: 'tooltip',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'tooltip',
  },
  {
    name: 'upload',
    type: 'registry:ui',
    dependencies: [],
    registryDependencies: [],
    root_folder: 'upload',
  },
]
