import { Registry } from '../registry-schema'

export const registry_examples: Registry = [
  {
    name: 'button-main',
    type: 'registry:example',
    registryDependencies: ['button'],
    root_folder: 'button',
    files: [],
  },
  {
    name: 'badge-main',
    type: 'registry:example',
    registryDependencies: ['badge'],
    root_folder: 'badge',
    files: [],
  },
  {
    name: 'tooltip-main',
    type: 'registry:example',
    registryDependencies: ['tooltip'],
    root_folder: 'tooltip',
    files: [],
  },
  {
    name: 'accordion-main',
    type: 'registry:example',
    registryDependencies: ['accordion'],
    root_folder: 'accordion',
    files: [],
  },
  {
    name: 'toggle-main',
    type: 'registry:example',
    registryDependencies: ['toggle'],
    root_folder: 'toggle',
    files: [],
  },
  {
    name: 'toggle-group-main',
    type: 'registry:example',
    registryDependencies: ['toggle-group'],
    root_folder: 'toggle-group',
    files: [],
  },
  {
    name: 'toast-main',
    type: 'registry:example',
    registryDependencies: ['toast'],
    root_folder: 'toast',
    files: [],
  },
  {
    name: 'sonner-main',
    type: 'registry:example',
    registryDependencies: ['sonner'],
    root_folder: 'sonner',
    files: [],
  },
  {
    name: 'textarea-main',
    type: 'registry:example',
    registryDependencies: ['textarea'],
    root_folder: 'textarea',
    files: [],
  },
  {
    name: 'tabs-main',
    type: 'registry:example',
    registryDependencies: ['tabs'],
    root_folder: 'tabs',
    files: [],
  },
  {
    name: 'table-main',
    type: 'registry:example',
    registryDependencies: ['table'],
    root_folder: 'table',
    files: [],
  },
  {
    name: 'upload-main',
    type: 'registry:example',
    registryDependencies: ['upload'],
    root_folder: 'upload',
    files: [],
  },
  {
    name: 'alert-dialog-main',
    type: 'registry:example',
    registryDependencies: ['alert-dialog', 'button'],
    root_folder: 'alert-dialog',
    files: [],
  },
  {
    name: 'drawer-main',
    type: 'registry:example',
    registryDependencies: ['drawer'],
    root_folder: 'drawer',
    files: [],
  },
]
