// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      type: "components:ui",
      registryDependencies: ["dialog"],
      component: React.lazy(() => import("@/registry/default/ui/button")),
      source: "",
      files: ["registry/default/ui/button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "badge": {
      name: "badge",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/badge")),
      source: "",
      files: ["registry/default/ui/badge.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "command": {
      name: "command",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/command")),
      source: "",
      files: ["registry/default/ui/command.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/tooltip")),
      source: "",
      files: ["registry/default/ui/tooltip.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "combobox": {
      name: "combobox",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/combobox")),
      source: "",
      files: ["registry/default/ui/combobox.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "nav-group": {
      name: "nav-group",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/nav-group")),
      source: "",
      files: ["registry/default/ui/nav-group.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "header": {
      name: "header",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/header")),
      source: "",
      files: ["registry/default/ui/header.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert-dialog": {
      name: "alert-dialog",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/alert-dialog")),
      source: "",
      files: ["registry/default/ui/alert-dialog.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "drawer": {
      name: "drawer",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/drawer")),
      source: "",
      files: ["registry/default/ui/drawer.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ButtonMainDemo": {
      name: "ButtonMainDemo",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/default/example/ButtonMainDemo")),
      source: "",
      files: ["registry/default/example/ButtonMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ButtonSimpleDemo": {
      name: "ButtonSimpleDemo",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/default/example/ButtonSimpleDemo")),
      source: "",
      files: ["registry/default/example/ButtonSimpleDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ButtonAdvancedDemo": {
      name: "ButtonAdvancedDemo",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/default/example/ButtonAdvancedDemo")),
      source: "",
      files: ["registry/default/example/ButtonAdvancedDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "BadgeMainDemo": {
      name: "BadgeMainDemo",
      type: "components:example",
      registryDependencies: ["badge"],
      component: React.lazy(() => import("@/registry/default/example/BadgeMainDemo")),
      source: "",
      files: ["registry/default/example/BadgeMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "CommandMainDemo": {
      name: "CommandMainDemo",
      type: "components:example",
      registryDependencies: ["command"],
      component: React.lazy(() => import("@/registry/default/example/CommandMainDemo")),
      source: "",
      files: ["registry/default/example/CommandMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "CommandDialogDemo": {
      name: "CommandDialogDemo",
      type: "components:example",
      registryDependencies: ["command"],
      component: React.lazy(() => import("@/registry/default/example/CommandDialogDemo")),
      source: "",
      files: ["registry/default/example/CommandDialogDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "CommandGroupDemo": {
      name: "CommandGroupDemo",
      type: "components:example",
      registryDependencies: ["tooltip"],
      component: React.lazy(() => import("@/registry/default/example/CommandGroupDemo")),
      source: "",
      files: ["registry/default/example/CommandGroupDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "TooltipMainDemo": {
      name: "TooltipMainDemo",
      type: "components:example",
      registryDependencies: ["tooltip"],
      component: React.lazy(() => import("@/registry/default/example/TooltipMainDemo")),
      source: "",
      files: ["registry/default/example/TooltipMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "TooltipGlobalDemo": {
      name: "TooltipGlobalDemo",
      type: "components:example",
      registryDependencies: ["tooltip"],
      component: React.lazy(() => import("@/registry/default/example/TooltipGlobalDemo")),
      source: "",
      files: ["registry/default/example/TooltipGlobalDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ComboboxMainDemo": {
      name: "ComboboxMainDemo",
      type: "components:example",
      registryDependencies: ["combobox"],
      component: React.lazy(() => import("@/registry/default/example/ComboboxMainDemo")),
      source: "",
      files: ["registry/default/example/ComboboxMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ComboboxDropdownDemo": {
      name: "ComboboxDropdownDemo",
      type: "components:example",
      registryDependencies: ["combobox"],
      component: React.lazy(() => import("@/registry/default/example/ComboboxDropdownDemo")),
      source: "",
      files: ["registry/default/example/ComboboxDropdownDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ComboboxResponsiveDemo": {
      name: "ComboboxResponsiveDemo",
      type: "components:example",
      registryDependencies: ["combobox"],
      component: React.lazy(() => import("@/registry/default/example/ComboboxResponsiveDemo")),
      source: "",
      files: ["registry/default/example/ComboboxResponsiveDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "NavGroupMainDemo": {
      name: "NavGroupMainDemo",
      type: "components:example",
      registryDependencies: ["nav-group"],
      component: React.lazy(() => import("@/registry/default/example/NavGroupMainDemo")),
      source: "",
      files: ["registry/default/example/NavGroupMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "HeaderMainDemo": {
      name: "HeaderMainDemo",
      type: "components:example",
      registryDependencies: ["header"],
      component: React.lazy(() => import("@/registry/default/example/HeaderMainDemo")),
      source: "",
      files: ["registry/default/example/HeaderMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "HeaderTopDemo": {
      name: "HeaderTopDemo",
      type: "components:example",
      registryDependencies: ["header"],
      component: React.lazy(() => import("@/registry/default/example/HeaderTopDemo")),
      source: "",
      files: ["registry/default/example/HeaderTopDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "AlertDialogMainDemo": {
      name: "AlertDialogMainDemo",
      type: "components:example",
      registryDependencies: ["alert-dialog","button"],
      component: React.lazy(() => import("@/registry/default/example/AlertDialogMainDemo")),
      source: "",
      files: ["registry/default/example/AlertDialogMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "AlertDialogDrawerDemo": {
      name: "AlertDialogDrawerDemo",
      type: "components:example",
      registryDependencies: ["alert-dialog","button","drawer","dialog","sheet"],
      component: React.lazy(() => import("@/registry/default/example/AlertDialogDrawerDemo")),
      source: "",
      files: ["registry/default/example/AlertDialogDrawerDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "AlertDialogSheetDemo": {
      name: "AlertDialogSheetDemo",
      type: "components:example",
      registryDependencies: ["alert-dialog","button","drawer","dialog","sheet"],
      component: React.lazy(() => import("@/registry/default/example/AlertDialogSheetDemo")),
      source: "",
      files: ["registry/default/example/AlertDialogSheetDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "AlertDialogDialogDemo": {
      name: "AlertDialogDialogDemo",
      type: "components:example",
      registryDependencies: ["alert-dialog","button","drawer","dialog","sheet"],
      component: React.lazy(() => import("@/registry/default/example/AlertDialogDialogDemo")),
      source: "",
      files: ["registry/default/example/AlertDialogDialogDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
