// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "Button": {
      name: "Button",
      type: "components:ui",
      registryDependencies: ["dialog"],
      component: React.lazy(() => import("@/registry/default/ui/Button")),
      source: "",
      files: ["registry/default/ui/Button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "Badge": {
      name: "Badge",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/Badge")),
      source: "",
      files: ["registry/default/ui/Badge.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "Command": {
      name: "Command",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/Command")),
      source: "",
      files: ["registry/default/ui/Command.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "Tooltip": {
      name: "Tooltip",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/ui/Tooltip")),
      source: "",
      files: ["registry/default/ui/Tooltip.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ButtonMainDemo": {
      name: "ButtonMainDemo",
      type: "components:example",
      registryDependencies: ["Button"],
      component: React.lazy(() => import("@/registry/default/example/ButtonMainDemo")),
      source: "",
      files: ["registry/default/example/ButtonMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ButtonSimpleDemo": {
      name: "ButtonSimpleDemo",
      type: "components:example",
      registryDependencies: ["Button"],
      component: React.lazy(() => import("@/registry/default/example/ButtonSimpleDemo")),
      source: "",
      files: ["registry/default/example/ButtonSimpleDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "ButtonAdvancedDemo": {
      name: "ButtonAdvancedDemo",
      type: "components:example",
      registryDependencies: ["Button"],
      component: React.lazy(() => import("@/registry/default/example/ButtonAdvancedDemo")),
      source: "",
      files: ["registry/default/example/ButtonAdvancedDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "BadgeMainDemo": {
      name: "BadgeMainDemo",
      type: "components:example",
      registryDependencies: ["Badge"],
      component: React.lazy(() => import("@/registry/default/example/BadgeMainDemo")),
      source: "",
      files: ["registry/default/example/BadgeMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "CommandMainDemo": {
      name: "CommandMainDemo",
      type: "components:example",
      registryDependencies: ["Command"],
      component: React.lazy(() => import("@/registry/default/example/CommandMainDemo")),
      source: "",
      files: ["registry/default/example/CommandMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "TooltipMainDemo": {
      name: "TooltipMainDemo",
      type: "components:example",
      registryDependencies: ["Command"],
      component: React.lazy(() => import("@/registry/default/example/TooltipMainDemo")),
      source: "",
      files: ["registry/default/example/TooltipMainDemo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
